

### 🔹 BASE CHECK
GET http://localhost:8080/api/quantity/all

###

### 🔹 CONVERT API
POST http://localhost:8080/api/quantity/convert
Content-Type: application/json

{
  "value": 10,
  "fromUnit": "FEET",
  "toUnit": "INCHES"
}

###

### 🔹 COMPARE API
POST http://localhost:8080/api/quantity/compare
Content-Type: application/json

{
  "q1": {
    "value": 1,
    "unit": "FEET"
  },
  "q2": {
    "value": 12,
    "unit": "INCHES"
  }
}

###

### 🔹 ADD API
POST http://localhost:8080/api/quantity/add
Content-Type: application/json

{
  "q1": {
    "value": 1,
    "unit": "FEET"
  },
  "q2": {
    "value": 12,
    "unit": "INCHES"
  }
}

###

### 🔹 SUBTRACT API
POST http://localhost:8080/api/quantity/subtract
Content-Type: application/json

{
  "q1": {
    "value": 2,
    "unit": "YARD"
  },
  "q2": {
    "value": 1,
    "unit": "FEET"
  }
}

###

### 🔹 DIVIDE API
POST http://localhost:8080/api/quantity/divide
Content-Type: application/json

{
  "q1": {
    "value": 10,
    "unit": "FEET"
  },
  "q2": {
    "value": 2,
    "unit": "FEET"
  }
}

###

### 🔹 GET ALL RECORDS
GET http://localhost:8080/api/quantity/all

###

### 🔹 GET BY ID
GET http://localhost:8080/api/quantity/1

###

### 🔹 DELETE BY ID
DELETE http://localhost:8080/api/quantity/1