server:
  port: ${PORT:8080} #Gateway kis port pe chalega

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors: #Ye frontend ko allow karta hai backend call karne ke liye
        corsConfigurations:
          '[/**]':   # Saari paths par CORS apply karo
            allowedOrigins:
              - "https://quantity-measurement-app-frontend-puce.vercel.app"
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600 # 1 ghante tak preflight cache karo

      discovery:
        locator:
          enabled: false #Static routing use ho raha hai not eureka kyuki services alag alag jagah deployed h

      # DedupeResponseHeader — safety net if downstream ever adds CORS headers again
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        #Duplicate headers remove karta hai First value rakhta hai

      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/auth/**

        - id: auth-oauth2
          uri: ${AUTH_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/oauth2/**

        - id: auth-login-oauth2
          uri: ${AUTH_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/login/oauth2/**

        - id: quantity-service
          uri: ${QUANTITY_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/quantity/**

        - id: history-service
          uri: ${HISTORY_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/history/**

eureka:
  client:
    enabled: false # Cross-platform pe discovery kaam nahi karta kyuki services different platforms pr padi hui h
    #humne yahan static routing use kiya hai instead of Eureka-based discovery kyunki services different platforms pe deployed hain

logging:
  level:
    org.springframework.cloud.gateway: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:

      show-details: always

      #Client (Frontend/Postman)
      #  ↓
      #CORS check (application.yml)
      #  ↓
      #LoggingFilter
      #  ↓
      #JwtAuthenticationFilter
      #  ↓
      #Routing (application.yml)
      #  ↓
      #Microservice
      #  ↓
      #Response
      #  ↓
      #LoggingFilter

#application.yml me maine Spring Cloud Gateway ke through CORS handling,
#static routing, and actuator-based monitoring configure kiya hai,
#jisse frontend communication secure aur microservice routing efficient ho jata ha