## Database Configuration
#db.url=jdbc:mysql://localhost:3306/quantity_measurement_db
#db.username=root
#db.password=AnushkaSinghal24
#db.driver=com.mysql.cj.jdbc.Driver
#
## Connection Pool
#db.pool.size=10
#
## Repository type
#repository.type=database

# App Name
spring.application.name=quantity-measurement-app

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement_db
spring.datasource.username=root
spring.datasource.password=RIDsriv9683@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
# Server Port (optional)
server.port=8080