#POST http://localhost:8082/api/auth/login?username=admin&password=admin

#POST http://localhost:8082/api/auth/signup
#Content-Type: application/json
#
#{
#  "username": "test2",
#  "password": "test123",
#  "role": "USER"
#}

#POST http://localhost:8082/api/auth/logout
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NDk3ODYyNCwiZXhwIjoxNzc0OTgyMjI0fQ.O0iI1bPnRA37PAOhWPB4HAGbxGpQHnRUaN_NRcJojlc

#GET http://localhost:8082/api/auth/profile
#Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NDk3ODU0MSwiZXhwIjoxNzc0OTgyMTQxfQ.kVJn0EbeB7c6ugoTIVZc3zmDrb97vUKKW0lRYsg4orI
#GET http://localhost:8082/api/auth/profile
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyaWRkaGkuc3JpdmFzdGF2YV9jczIyQGdsYS5hYy5pbiIsImlhdCI6MTc3NTAzNDU5MCwiZXhwIjoxNzc1MDM4MTkwfQ.2X2ytDDqN53prFlKQh8tVKHz64FLWXgOMkDVfTWb31k


http://localhost:8082/api/quantity/convert/feet-to-inch?value=2

#GET http://localhost:8082/api/auth/profile
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyaWRkaGkuc3JpdmFzdGF2YV9jczIyQGdsYS5hYy5pbiIsImlhdCI6MTc3NTAzNjM1OCwiZXhwIjoxNzc1MDM5OTU4fQ.BJiTxzx3xFNYCwlnlhC3AphjwFPuROW7YBImVDtoqOM