spring.application.name=eureka-server

server.port=${PORT:8761} 
#Railway inject karta hai PORT env var

eureka.client.register-with-eureka=false
#Server khud ko register nahi karega Kyunki ye already registry hai
#Service ka naam define karta hai
#Server khud ko register nahi karta ? woh registry hai, client nahi


eureka.client.fetch-registry=false
#Ye dusre Eureka servers se data fetch nahi karega
# Server dusri registries se data fetch nahi karta
# (Agar cluster setup ho toh true karte ? yahan single node hai)


# Optional (safe to include)
eureka.instance.hostname=localhost
#Server ka hostname define karta hai